import * as drizzle_orm_pg_core157 from "drizzle-orm/pg-core";

//#region src/migrations/schema.d.ts
declare const etapa: drizzle_orm_pg_core157.PgEnum<["bercario", "maternal", "pre_escola", "fundamental"]>;
declare const formatoRelatorio: drizzle_orm_pg_core157.PgEnum<["pdf", "csv"]>;
declare const statusDocumento: drizzle_orm_pg_core157.PgEnum<["pendente", "anexado", "aprovado"]>;
declare const statusMatricula: drizzle_orm_pg_core157.PgEnum<["pre", "pendente_doc", "completo", "concluido"]>;
declare const tipoDocumento: drizzle_orm_pg_core157.PgEnum<["certidao", "rg_cpf_resp", "vacina", "residencia", "historico", "foto3x4"]>;
declare const tipoRelatorio: drizzle_orm_pg_core157.PgEnum<["matriculas", "pre_matriculas", "turmas", "documentos", "pendencias", "geral"]>;
declare const turno: drizzle_orm_pg_core157.PgEnum<["manha", "tarde", "integral"]>;
declare const relatorioGerado: drizzle_orm_pg_core157.PgTableWithColumns<{
  name: "relatorio_gerado";
  schema: undefined;
  columns: {
    id: drizzle_orm_pg_core157.PgColumn<{
      name: "id";
      tableName: "relatorio_gerado";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: true;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    tipo: drizzle_orm_pg_core157.PgColumn<{
      name: "tipo";
      tableName: "relatorio_gerado";
      dataType: "string";
      columnType: "PgEnumColumn";
      data: "matriculas" | "pre_matriculas" | "turmas" | "documentos" | "pendencias" | "geral";
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: ["matriculas", "pre_matriculas", "turmas", "documentos", "pendencias", "geral"];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    formato: drizzle_orm_pg_core157.PgColumn<{
      name: "formato";
      tableName: "relatorio_gerado";
      dataType: "string";
      columnType: "PgEnumColumn";
      data: "pdf" | "csv";
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: ["pdf", "csv"];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    filtros: drizzle_orm_pg_core157.PgColumn<{
      name: "filtros";
      tableName: "relatorio_gerado";
      dataType: "json";
      columnType: "PgJsonb";
      data: unknown;
      driverParam: unknown;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    usuarioId: drizzle_orm_pg_core157.PgColumn<{
      name: "usuario_id";
      tableName: "relatorio_gerado";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    nomeArquivo: drizzle_orm_pg_core157.PgColumn<{
      name: "nome_arquivo";
      tableName: "relatorio_gerado";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    tamanhoArquivo: drizzle_orm_pg_core157.PgColumn<{
      name: "tamanho_arquivo";
      tableName: "relatorio_gerado";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    createdAt: drizzle_orm_pg_core157.PgColumn<{
      name: "created_at";
      tableName: "relatorio_gerado";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
  };
  dialect: "pg";
}>;
declare const verification: drizzle_orm_pg_core157.PgTableWithColumns<{
  name: "verification";
  schema: undefined;
  columns: {
    id: drizzle_orm_pg_core157.PgColumn<{
      name: "id";
      tableName: "verification";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: true;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    identifier: drizzle_orm_pg_core157.PgColumn<{
      name: "identifier";
      tableName: "verification";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    value: drizzle_orm_pg_core157.PgColumn<{
      name: "value";
      tableName: "verification";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    expiresAt: drizzle_orm_pg_core157.PgColumn<{
      name: "expiresAt";
      tableName: "verification";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    createdAt: drizzle_orm_pg_core157.PgColumn<{
      name: "createdAt";
      tableName: "verification";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    updatedAt: drizzle_orm_pg_core157.PgColumn<{
      name: "updatedAt";
      tableName: "verification";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
  };
  dialect: "pg";
}>;
declare const account: drizzle_orm_pg_core157.PgTableWithColumns<{
  name: "account";
  schema: undefined;
  columns: {
    id: drizzle_orm_pg_core157.PgColumn<{
      name: "id";
      tableName: "account";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: true;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    accountId: drizzle_orm_pg_core157.PgColumn<{
      name: "accountId";
      tableName: "account";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    providerId: drizzle_orm_pg_core157.PgColumn<{
      name: "providerId";
      tableName: "account";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    userId: drizzle_orm_pg_core157.PgColumn<{
      name: "userId";
      tableName: "account";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    accessToken: drizzle_orm_pg_core157.PgColumn<{
      name: "accessToken";
      tableName: "account";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    refreshToken: drizzle_orm_pg_core157.PgColumn<{
      name: "refreshToken";
      tableName: "account";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    idToken: drizzle_orm_pg_core157.PgColumn<{
      name: "idToken";
      tableName: "account";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    accessTokenExpiresAt: drizzle_orm_pg_core157.PgColumn<{
      name: "accessTokenExpiresAt";
      tableName: "account";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    refreshTokenExpiresAt: drizzle_orm_pg_core157.PgColumn<{
      name: "refreshTokenExpiresAt";
      tableName: "account";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    scope: drizzle_orm_pg_core157.PgColumn<{
      name: "scope";
      tableName: "account";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    password: drizzle_orm_pg_core157.PgColumn<{
      name: "password";
      tableName: "account";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    createdAt: drizzle_orm_pg_core157.PgColumn<{
      name: "createdAt";
      tableName: "account";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    updatedAt: drizzle_orm_pg_core157.PgColumn<{
      name: "updatedAt";
      tableName: "account";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
  };
  dialect: "pg";
}>;
declare const session: drizzle_orm_pg_core157.PgTableWithColumns<{
  name: "session";
  schema: undefined;
  columns: {
    id: drizzle_orm_pg_core157.PgColumn<{
      name: "id";
      tableName: "session";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: true;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    expiresAt: drizzle_orm_pg_core157.PgColumn<{
      name: "expiresAt";
      tableName: "session";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    token: drizzle_orm_pg_core157.PgColumn<{
      name: "token";
      tableName: "session";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    createdAt: drizzle_orm_pg_core157.PgColumn<{
      name: "createdAt";
      tableName: "session";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    updatedAt: drizzle_orm_pg_core157.PgColumn<{
      name: "updatedAt";
      tableName: "session";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    ipAddress: drizzle_orm_pg_core157.PgColumn<{
      name: "ipAddress";
      tableName: "session";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    userAgent: drizzle_orm_pg_core157.PgColumn<{
      name: "userAgent";
      tableName: "session";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    userId: drizzle_orm_pg_core157.PgColumn<{
      name: "userId";
      tableName: "session";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
  };
  dialect: "pg";
}>;
declare const user: drizzle_orm_pg_core157.PgTableWithColumns<{
  name: "user";
  schema: undefined;
  columns: {
    id: drizzle_orm_pg_core157.PgColumn<{
      name: "id";
      tableName: "user";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: true;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    name: drizzle_orm_pg_core157.PgColumn<{
      name: "name";
      tableName: "user";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    email: drizzle_orm_pg_core157.PgColumn<{
      name: "email";
      tableName: "user";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    emailVerified: drizzle_orm_pg_core157.PgColumn<{
      name: "emailVerified";
      tableName: "user";
      dataType: "boolean";
      columnType: "PgBoolean";
      data: boolean;
      driverParam: boolean;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    image: drizzle_orm_pg_core157.PgColumn<{
      name: "image";
      tableName: "user";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    createdAt: drizzle_orm_pg_core157.PgColumn<{
      name: "createdAt";
      tableName: "user";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    updatedAt: drizzle_orm_pg_core157.PgColumn<{
      name: "updatedAt";
      tableName: "user";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    role: drizzle_orm_pg_core157.PgColumn<{
      name: "role";
      tableName: "user";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
  };
  dialect: "pg";
}>;
declare const aluno: drizzle_orm_pg_core157.PgTableWithColumns<{
  name: "aluno";
  schema: undefined;
  columns: {
    id: drizzle_orm_pg_core157.PgColumn<{
      name: "id";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: true;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    idGlobal: drizzle_orm_pg_core157.PgColumn<{
      name: "id_global";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    nome: drizzle_orm_pg_core157.PgColumn<{
      name: "nome";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    dataNascimento: drizzle_orm_pg_core157.PgColumn<{
      name: "data_nascimento";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    etapa: drizzle_orm_pg_core157.PgColumn<{
      name: "etapa";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgEnumColumn";
      data: "bercario" | "maternal" | "pre_escola" | "fundamental";
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: ["bercario", "maternal", "pre_escola", "fundamental"];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    status: drizzle_orm_pg_core157.PgColumn<{
      name: "status";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgEnumColumn";
      data: "pre" | "pendente_doc" | "completo" | "concluido";
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: ["pre", "pendente_doc", "completo", "concluido"];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    necessidadesEspeciais: drizzle_orm_pg_core157.PgColumn<{
      name: "necessidades_especiais";
      tableName: "aluno";
      dataType: "boolean";
      columnType: "PgBoolean";
      data: boolean;
      driverParam: boolean;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    observacoes: drizzle_orm_pg_core157.PgColumn<{
      name: "observacoes";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    createdAt: drizzle_orm_pg_core157.PgColumn<{
      name: "created_at";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    updatedAt: drizzle_orm_pg_core157.PgColumn<{
      name: "updated_at";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    rg: drizzle_orm_pg_core157.PgColumn<{
      name: "rg";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    cpf: drizzle_orm_pg_core157.PgColumn<{
      name: "cpf";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    naturalidade: drizzle_orm_pg_core157.PgColumn<{
      name: "naturalidade";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    nacionalidade: drizzle_orm_pg_core157.PgColumn<{
      name: "nacionalidade";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    sexo: drizzle_orm_pg_core157.PgColumn<{
      name: "sexo";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    corRaca: drizzle_orm_pg_core157.PgColumn<{
      name: "cor_raca";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    tipoSanguineo: drizzle_orm_pg_core157.PgColumn<{
      name: "tipo_sanguineo";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    alergias: drizzle_orm_pg_core157.PgColumn<{
      name: "alergias";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    medicamentos: drizzle_orm_pg_core157.PgColumn<{
      name: "medicamentos";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    doencas: drizzle_orm_pg_core157.PgColumn<{
      name: "doencas";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    carteiraVacina: drizzle_orm_pg_core157.PgColumn<{
      name: "carteira_vacina";
      tableName: "aluno";
      dataType: "boolean";
      columnType: "PgBoolean";
      data: boolean;
      driverParam: boolean;
      notNull: false;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    observacoesSaude: drizzle_orm_pg_core157.PgColumn<{
      name: "observacoes_saude";
      tableName: "aluno";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
  };
  dialect: "pg";
}>;
declare const pendencia: drizzle_orm_pg_core157.PgTableWithColumns<{
  name: "pendencia";
  schema: undefined;
  columns: {
    id: drizzle_orm_pg_core157.PgColumn<{
      name: "id";
      tableName: "pendencia";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: true;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    matriculaId: drizzle_orm_pg_core157.PgColumn<{
      name: "matricula_id";
      tableName: "pendencia";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    documentoId: drizzle_orm_pg_core157.PgColumn<{
      name: "documento_id";
      tableName: "pendencia";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    descricao: drizzle_orm_pg_core157.PgColumn<{
      name: "descricao";
      tableName: "pendencia";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    prazo: drizzle_orm_pg_core157.PgColumn<{
      name: "prazo";
      tableName: "pendencia";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    resolvido: drizzle_orm_pg_core157.PgColumn<{
      name: "resolvido";
      tableName: "pendencia";
      dataType: "boolean";
      columnType: "PgBoolean";
      data: boolean;
      driverParam: boolean;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    dataResolucao: drizzle_orm_pg_core157.PgColumn<{
      name: "data_resolucao";
      tableName: "pendencia";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    observacoes: drizzle_orm_pg_core157.PgColumn<{
      name: "observacoes";
      tableName: "pendencia";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    createdAt: drizzle_orm_pg_core157.PgColumn<{
      name: "created_at";
      tableName: "pendencia";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    updatedAt: drizzle_orm_pg_core157.PgColumn<{
      name: "updated_at";
      tableName: "pendencia";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
  };
  dialect: "pg";
}>;
declare const matricula: drizzle_orm_pg_core157.PgTableWithColumns<{
  name: "matricula";
  schema: undefined;
  columns: {
    id: drizzle_orm_pg_core157.PgColumn<{
      name: "id";
      tableName: "matricula";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: true;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    idGlobal: drizzle_orm_pg_core157.PgColumn<{
      name: "id_global";
      tableName: "matricula";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    protocoloLocal: drizzle_orm_pg_core157.PgColumn<{
      name: "protocolo_local";
      tableName: "matricula";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    alunoId: drizzle_orm_pg_core157.PgColumn<{
      name: "aluno_id";
      tableName: "matricula";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    responsavelId: drizzle_orm_pg_core157.PgColumn<{
      name: "responsavel_id";
      tableName: "matricula";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    turmaId: drizzle_orm_pg_core157.PgColumn<{
      name: "turma_id";
      tableName: "matricula";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    status: drizzle_orm_pg_core157.PgColumn<{
      name: "status";
      tableName: "matricula";
      dataType: "string";
      columnType: "PgEnumColumn";
      data: "pre" | "pendente_doc" | "completo" | "concluido";
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: ["pre", "pendente_doc", "completo", "concluido"];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    dataMatricula: drizzle_orm_pg_core157.PgColumn<{
      name: "data_matricula";
      tableName: "matricula";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    observacoes: drizzle_orm_pg_core157.PgColumn<{
      name: "observacoes";
      tableName: "matricula";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    createdAt: drizzle_orm_pg_core157.PgColumn<{
      name: "created_at";
      tableName: "matricula";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    updatedAt: drizzle_orm_pg_core157.PgColumn<{
      name: "updated_at";
      tableName: "matricula";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
  };
  dialect: "pg";
}>;
declare const documento: drizzle_orm_pg_core157.PgTableWithColumns<{
  name: "documento";
  schema: undefined;
  columns: {
    id: drizzle_orm_pg_core157.PgColumn<{
      name: "id";
      tableName: "documento";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: true;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    matriculaId: drizzle_orm_pg_core157.PgColumn<{
      name: "matricula_id";
      tableName: "documento";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    tipo: drizzle_orm_pg_core157.PgColumn<{
      name: "tipo";
      tableName: "documento";
      dataType: "string";
      columnType: "PgEnumColumn";
      data: "certidao" | "rg_cpf_resp" | "vacina" | "residencia" | "historico" | "foto3x4";
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: ["certidao", "rg_cpf_resp", "vacina", "residencia", "historico", "foto3x4"];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    status: drizzle_orm_pg_core157.PgColumn<{
      name: "status";
      tableName: "documento";
      dataType: "string";
      columnType: "PgEnumColumn";
      data: "pendente" | "anexado" | "aprovado";
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: ["pendente", "anexado", "aprovado"];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    arquivoUrl: drizzle_orm_pg_core157.PgColumn<{
      name: "arquivo_url";
      tableName: "documento";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    nomeArquivo: drizzle_orm_pg_core157.PgColumn<{
      name: "nome_arquivo";
      tableName: "documento";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    tamanhoArquivo: drizzle_orm_pg_core157.PgColumn<{
      name: "tamanho_arquivo";
      tableName: "documento";
      dataType: "number";
      columnType: "PgInteger";
      data: number;
      driverParam: string | number;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    observacoes: drizzle_orm_pg_core157.PgColumn<{
      name: "observacoes";
      tableName: "documento";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    createdAt: drizzle_orm_pg_core157.PgColumn<{
      name: "created_at";
      tableName: "documento";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    updatedAt: drizzle_orm_pg_core157.PgColumn<{
      name: "updated_at";
      tableName: "documento";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
  };
  dialect: "pg";
}>;
declare const turma: drizzle_orm_pg_core157.PgTableWithColumns<{
  name: "turma";
  schema: undefined;
  columns: {
    id: drizzle_orm_pg_core157.PgColumn<{
      name: "id";
      tableName: "turma";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: true;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    idGlobal: drizzle_orm_pg_core157.PgColumn<{
      name: "id_global";
      tableName: "turma";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    etapa: drizzle_orm_pg_core157.PgColumn<{
      name: "etapa";
      tableName: "turma";
      dataType: "string";
      columnType: "PgEnumColumn";
      data: "bercario" | "maternal" | "pre_escola" | "fundamental";
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: ["bercario", "maternal", "pre_escola", "fundamental"];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    turno: drizzle_orm_pg_core157.PgColumn<{
      name: "turno";
      tableName: "turma";
      dataType: "string";
      columnType: "PgEnumColumn";
      data: "manha" | "tarde" | "integral";
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: ["manha", "tarde", "integral"];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    capacidade: drizzle_orm_pg_core157.PgColumn<{
      name: "capacidade";
      tableName: "turma";
      dataType: "number";
      columnType: "PgInteger";
      data: number;
      driverParam: string | number;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    vagasDisponiveis: drizzle_orm_pg_core157.PgColumn<{
      name: "vagas_disponiveis";
      tableName: "turma";
      dataType: "number";
      columnType: "PgInteger";
      data: number;
      driverParam: string | number;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    anoLetivo: drizzle_orm_pg_core157.PgColumn<{
      name: "ano_letivo";
      tableName: "turma";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    nome: drizzle_orm_pg_core157.PgColumn<{
      name: "nome";
      tableName: "turma";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    ativa: drizzle_orm_pg_core157.PgColumn<{
      name: "ativa";
      tableName: "turma";
      dataType: "boolean";
      columnType: "PgBoolean";
      data: boolean;
      driverParam: boolean;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    createdAt: drizzle_orm_pg_core157.PgColumn<{
      name: "created_at";
      tableName: "turma";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    updatedAt: drizzle_orm_pg_core157.PgColumn<{
      name: "updated_at";
      tableName: "turma";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
  };
  dialect: "pg";
}>;
declare const contatoEmergencia: drizzle_orm_pg_core157.PgTableWithColumns<{
  name: "contato_emergencia";
  schema: undefined;
  columns: {
    id: drizzle_orm_pg_core157.PgColumn<{
      name: "id";
      tableName: "contato_emergencia";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: true;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    matriculaId: drizzle_orm_pg_core157.PgColumn<{
      name: "matricula_id";
      tableName: "contato_emergencia";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    nome: drizzle_orm_pg_core157.PgColumn<{
      name: "nome";
      tableName: "contato_emergencia";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    telefone: drizzle_orm_pg_core157.PgColumn<{
      name: "telefone";
      tableName: "contato_emergencia";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    parentesco: drizzle_orm_pg_core157.PgColumn<{
      name: "parentesco";
      tableName: "contato_emergencia";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    observacoes: drizzle_orm_pg_core157.PgColumn<{
      name: "observacoes";
      tableName: "contato_emergencia";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    createdAt: drizzle_orm_pg_core157.PgColumn<{
      name: "created_at";
      tableName: "contato_emergencia";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    updatedAt: drizzle_orm_pg_core157.PgColumn<{
      name: "updated_at";
      tableName: "contato_emergencia";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
  };
  dialect: "pg";
}>;
declare const responsavel: drizzle_orm_pg_core157.PgTableWithColumns<{
  name: "responsavel";
  schema: undefined;
  columns: {
    id: drizzle_orm_pg_core157.PgColumn<{
      name: "id";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: true;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    idGlobal: drizzle_orm_pg_core157.PgColumn<{
      name: "id_global";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    nome: drizzle_orm_pg_core157.PgColumn<{
      name: "nome";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    cpf: drizzle_orm_pg_core157.PgColumn<{
      name: "cpf";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    telefone: drizzle_orm_pg_core157.PgColumn<{
      name: "telefone";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    endereco: drizzle_orm_pg_core157.PgColumn<{
      name: "endereco";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    bairro: drizzle_orm_pg_core157.PgColumn<{
      name: "bairro";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    email: drizzle_orm_pg_core157.PgColumn<{
      name: "email";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    parentesco: drizzle_orm_pg_core157.PgColumn<{
      name: "parentesco";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    autorizadoRetirada: drizzle_orm_pg_core157.PgColumn<{
      name: "autorizado_retirada";
      tableName: "responsavel";
      dataType: "boolean";
      columnType: "PgBoolean";
      data: boolean;
      driverParam: boolean;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    createdAt: drizzle_orm_pg_core157.PgColumn<{
      name: "created_at";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    updatedAt: drizzle_orm_pg_core157.PgColumn<{
      name: "updated_at";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: true;
      hasDefault: true;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    rg: drizzle_orm_pg_core157.PgColumn<{
      name: "rg";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    dataNascimento: drizzle_orm_pg_core157.PgColumn<{
      name: "data_nascimento";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgTimestampString";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: undefined;
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    naturalidade: drizzle_orm_pg_core157.PgColumn<{
      name: "naturalidade";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    nacionalidade: drizzle_orm_pg_core157.PgColumn<{
      name: "nacionalidade";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    sexo: drizzle_orm_pg_core157.PgColumn<{
      name: "sexo";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    estadoCivil: drizzle_orm_pg_core157.PgColumn<{
      name: "estado_civil";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    profissao: drizzle_orm_pg_core157.PgColumn<{
      name: "profissao";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    localTrabalho: drizzle_orm_pg_core157.PgColumn<{
      name: "local_trabalho";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    telefoneTrabalho: drizzle_orm_pg_core157.PgColumn<{
      name: "telefone_trabalho";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    contatoEmergencia: drizzle_orm_pg_core157.PgColumn<{
      name: "contato_emergencia";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    telefoneEmergencia: drizzle_orm_pg_core157.PgColumn<{
      name: "telefone_emergencia";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
    parentescoEmergencia: drizzle_orm_pg_core157.PgColumn<{
      name: "parentesco_emergencia";
      tableName: "responsavel";
      dataType: "string";
      columnType: "PgText";
      data: string;
      driverParam: string;
      notNull: false;
      hasDefault: false;
      isPrimaryKey: false;
      isAutoincrement: false;
      hasRuntimeDefault: false;
      enumValues: [string, ...string[]];
      baseColumn: never;
      identity: undefined;
      generated: undefined;
    }, {}, {}>;
  };
  dialect: "pg";
}>;
//#endregion
export { account, aluno, contatoEmergencia, documento, etapa, formatoRelatorio, matricula, pendencia, relatorioGerado, responsavel, session, statusDocumento, statusMatricula, tipoDocumento, tipoRelatorio, turma, turno, user, verification };
//# sourceMappingURL=schema.d.ts.map